#!/bin/bash
# Screens new GitHub repos as candidates for architectural-smell analysis with Designite.
# Usage:   bash scripts/screen.sh
# Output:  data/screened.tsv  repos Designite can analyze (repo, namespaces, .csproj files, lines of C#, solution type),
#                        most namespaces first
#          data/skipped.tsv   repos left out, with the reason (clone failed / Unity project / no .csproj)

# ---- settings: adjust these ----
LANGUAGE="csharp"
CREATED_AFTER="2026-07-01"   # set this to after your LLM's training data cutoff
MIN_SIZE_KB=500
MAX_SIZE_KB=20000
LIMIT=100

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
mkdir -p "$ROOT/data" && cd "$ROOT/data" || exit 1   # all files below are written to data/

export GIT_TERMINAL_PROMPT=0   # never wait for a password (deleted or private repos)
export GIT_LFS_SKIP_SMUDGE=1   # don't download Git LFS files (images, binaries)

# 1) Find candidate repos
echo "Searching GitHub..."
gh search repos --language="$LANGUAGE" --created=">$CREATED_AFTER" --size="$MIN_SIZE_KB..$MAX_SIZE_KB" \
  --archived=false --limit "$LIMIT" --json fullName --jq '.[].fullName' > candidates.txt || exit 1
total=$(wc -l < candidates.txt | tr -d ' ')
echo "Found $total candidates."

# 2) Check and measure each repo (only C# sources, project/solution files and Unity's marker file are downloaded)
: > results.tsv
: > skipped.tsv
i=0
while read -r repo; do
  i=$((i + 1))
  echo "[$i/$total] $repo"
  dir=$(mktemp -d)
  if ! git clone -q --depth 1 --filter=blob:none --sparse "https://github.com/$repo" "$dir" </dev/null 2>/dev/null; then
    echo "    skipped: clone failed"
    printf '%s\tclone failed\n' "$repo" >> skipped.tsv
    rm -rf "$dir"
    continue
  fi
  git -C "$dir" sparse-checkout set --no-cone '*.cs' '*.csproj' '*.sln' '*.slnx' \
    '**/ProjectSettings/ProjectVersion.txt' </dev/null 2>/dev/null

  # Unity projects: their .sln/.csproj files are generated by the Unity editor, so Designite can't load them
  if [ -n "$(find "$dir" -path '*/ProjectSettings/ProjectVersion.txt' | head -1)" ]; then
    echo "    skipped: Unity project"
    printf '%s\tUnity project\n' "$repo" >> skipped.tsv
    rm -rf "$dir"
    continue
  fi

  proj=$(find "$dir" -name '*.csproj' | wc -l)
  if [ "$proj" -eq 0 ]; then
    echo "    skipped: no .csproj"
    printf '%s\tno .csproj\n' "$repo" >> skipped.tsv
    rm -rf "$dir"
    continue
  fi

  # Solution type: "sln" works directly; "slnx-only" needs a classic .sln created first; "none" = only .csproj files
  if [ -n "$(find "$dir" -name '*.sln' | head -1)" ]; then
    sol="sln"
  elif [ -n "$(find "$dir" -name '*.slnx' | head -1)" ]; then
    sol="slnx-only"
  else
    sol="none"
  fi

  ns=$(grep -rhoE '^[[:space:]]*namespace[[:space:]]+[A-Za-z0-9_.]+' --include='*.cs' "$dir" | awk '{print $2}' | sort -u | wc -l)
  loc=$(find "$dir" -name '*.cs' -exec cat {} + | wc -l)
  printf '%s\t%d\t%d\t%d\t%s\n' "$repo" "$ns" "$proj" "$loc" "$sol" >> results.tsv
  rm -rf "$dir"
done < candidates.txt

# 3) Sort by number of namespaces and show the top 20
{ printf 'repo\tnamespaces\tprojects\tloc\tsolution\n'; sort -t$'\t' -k2 -nr results.tsv; } > screened.tsv
kept=$(wc -l < results.tsv | tr -d ' ')
skipped=$(wc -l < skipped.tsv | tr -d ' ')
echo
if command -v column >/dev/null; then column -t -s $'\t' screened.tsv | head -21; else head -21 screened.tsv; fi
echo
echo "Kept $kept repos -> data/screened.tsv"
echo "Skipped $skipped repos -> data/skipped.tsv"
